name: test github action in a project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: holishing/gfortran_autotool_action@2020.308.proto
