# This is a basic workflow to help you get started with Actions

name: test github action in a project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        content: ["","--host=i686-w64-mingw64","--host=i686-w64-mingw32"]
    steps:
    - uses: actions/checkout@v2
    - name: test again
      uses: holishing/gfortran_autotool_action@2020.308.z0008
      with:
        matrix:
        args:  ${{ matrix.content }}
